# Configuración centralizada del juego
import pygame

# Pantalla
ANCHO_PANTALLA = 800
ALTO_PANTALLA = 600
TITULO_VENTANA = "Pizza Survivor"

# Límites del repartidor
LIMITE_REPARTIDOR_X = (0, 736)
LIMITE_REPARTIDOR_Y = (0, 500)

# Repartidor
VELOCIDAD_REPARTIDOR = 1
REPARTIDOR_ANCHO = 64
REPARTIDOR_ALTO = 100

# Enemigos
ANCHO_PANTALLA_SPAWN = 800
ALTO_PANTALLA_SPAWN = 600

# Proyectiles
RADIO_COLISION_PROYECTIL = 30

# Vidas
VIDAS_INICIALES = 3
DURACION_INVULNERABILIDAD = 1000

# Dificultad
INTERVALO_SPAWN_INICIAL = 2500
INTERVALO_SPAWN_MINIMO = 1000
DECREMENTO_SPAWN = 50

# Lanzamiento
INTERVALO_LANZAMIENTO = 1500

# Sonidos
VOLUMEN_MUSICA = 0.3
VOLUMEN_SONIDOS = 0.7

# Estados del juego
ESTADO_JUGANDO = "jugando"
ESTADO_TERMINADO = "terminado"
